### ISSUE TITLE
Chunking in frequency may cause excessive memory use

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/dask-ms#163]
* dask-ms version: master
* Python version: 3.8.8
* Operating System: Pop!_OS 18.04

### Description

While running my small example case, chunking in frequency causes bizarre memory behaviour.

### What I Did

I don't have a reproducer, but it boils down to reading a measurement set while chunking in frequency.

### What happened?

![Screenshot from 2021-06-08 11-14-10](https://user-images.githubusercontent.com/6582745/121158453-ab2e3780-c84a-11eb-9197-d0321486f163.png)

The memory usage grows, seemingly without bound, over time. Contrast this with reading from zarr:

![Screenshot from 2021-06-08 11-18-11](https://user-images.githubusercontent.com/6582745/121159154-3c051300-c84b-11eb-9eaf-71823df3e37d.png)

### Why?

My best guess is that this is a problem with the way casacore caches data for tiled columns. Dask does not process chunks in a consistent order - I believe that this leads to the all the tiled columns being cached in their entirety. This may only happen when the frequency chunk is smaller than the frequency tiling of the MS.

**Comment by sjperkins** [comment]
Related to:

- https://github.com/ska-sa/dask-ms/issues/92
- https://github.com/ska-sa/dask-ms/pull/107

Also, recalling our conversation, changing the number of frequency chunks did not increase or decrease the amount of memory used in the CASA Table case.

**Comment by JSKenyon** [comment]
Closing as this is mainly an edge case. This should only happen when data is poorly tiled/very small.
