### ISSUE TITLE
Support taql query when converting from CASA format

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/dask-ms#263]
This would be a very handy feature. Currently I find myself splitting with CASA and then converting to zarr which is not so friendly to disc space. This can obviously only work when converting from a measurement set. I am not sure if it makes sense to support this for the other formats but it may be nice to also have taql-like selection logic (or some subset thereof) when we eventually have support to convert directly from katdal format

**Comment by sjperkins** [comment]
It should be possible to add a `--taql-where` flag
