### ISSUE TITLE
Dask version semantics overly strict in pyproject.toml

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/dask-ms#278]
* dask-ms version: master
* Python version: 3.8.10
* Operating System: Ubuntu 20.04 LTS

### Description

I believe that some of my dependency woes stem from the `^version` syntax in `pyproject.toml`. The versioning of `dask` means that `^2022.9.1` will never allow the installation of a `2023.x.x` version. Would it be more sensible to specify `>=2022.9.1`?

**Comment by sjperkins** [comment]
Yep, let me try this locally
