### ISSUE TITLE
Python-casacore dependencies are too strict, add support back for python3.8

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/dask-ms#305]
Two issues with supporting the existing ecosystem:
- At the moment the version pinning of dask-ms is too strict to properly support migrating the existing ecosystem over (https://github.com/cyriltasse/DDFacet/pull/865 for instance rely targeting  Python 3.8 - which is our current LTS version). 
- The version pinning on python-casacore is also too strict 3.5 has only very recently released. I have successfully tested downpinning casacore back to v3.3.1 with dask-ms tests passing for 3.3.1 and 3.4. 

I will make a PR here to bring back support for Python 3.8 and python-casacore v3.3.1 in order to get @o-smirnov's dask-ms porting of backends to more recent versions of dask-ms.

**Comment by sjperkins** [comment]
Closing, for reasons discussed here https://github.com/ratt-ru/dask-ms/pull/306#issuecomment-1898079125
